#!/bin/bash
DIR=$(dirname $0)

VERSION=0.0.2
SNAPSHOT_PATH="$DIR/target/chatter-$VERSION-SNAPSHOT-jar-with-dependencies.jar"
RELEASE_PATH="$DIR/target/chatter-$VERSION-jar-with-dependencies.jar"
DOWNLOAD_URL="https://github.com/pepe79/construqt/raw/mvn-repo/me/construqt/ciscian/chatter/$VERSION/chatter-$VERSION-jar-with-dependencies.jar"

if [ -e $SNAPSHOT_PATH ]
then
  >&2 echo "Using snapshot version of switch chatter."
  SC_JAR=$SNAPSHOT_PATH
else
  if [ -e $RELEASE_PATH ]
  then
    >&2 echo "Using previously downloaded version of switch chatter."
  else
    >&2 echo "Downloading switch chatter jar..."
    wget --no-verbose --directory-prefix="$DIR/target" $DOWNLOAD_URL
  fi
  SC_JAR=$RELEASE_PATH
fi
if [ -f /usr/bin/cygpath.exe ] 
  then 
  $SC_JAR="`/usr/bin/cygpath.exe -w $SC_JAR`"
fi

java -Djava.net.preferIPv4Stack=false -jar $SC_JAR $1 $2 $3 $4 $5 $6 $7 $8
